sudo: required
services:
  - docker

before_install:
  - docker build -t kalvete/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalvete/react-test npm test

after_success:
  - docker build -t kalvete/complexcalc-client ./client
  - docker build -t kalvete/complexcalc-nginx ./nginx
  - docker build -t kalvete/complexcalc-server ./server
  - docker build -t kalvete/complexcalc-worker ./worker 

  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push kalvete/complexcalc-client
  - docker push kalvete/complexcalc-nginx
  - docker push kalvete/complexcalc-server
  - docker push kalvete/complexcalc-worker
  -
  -
  -