sudo: required
services:
  - docker

before_install:
  - docker build -t alvete/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alvete/react-test npm test

after_success:
  - docker build -t alvete/complexcalc-client ./client
  - docker build -t alvete/complexcalc-nginx ./nginx
  - docker build -t alvete/complexcalc-server ./server
  - docker build -t alvete/complexcalc-worker ./worker 